package com.example.dllo.newbaidumusic.mydb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dllo.newbaidumusic.mydb.LikeSongBean;

import com.example.dllo.newbaidumusic.mydb.LikeSongBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeSongBeanDaoConfig;

    private final LikeSongBeanDao likeSongBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeSongBeanDaoConfig = daoConfigMap.get(LikeSongBeanDao.class).clone();
        likeSongBeanDaoConfig.initIdentityScope(type);

        likeSongBeanDao = new LikeSongBeanDao(likeSongBeanDaoConfig, this);

        registerDao(LikeSongBean.class, likeSongBeanDao);
    }
    
    public void clear() {
        likeSongBeanDaoConfig.clearIdentityScope();
    }

    public LikeSongBeanDao getLikeSongBeanDao() {
        return likeSongBeanDao;
    }

}
